config:
  registries:
    - name: ECR
      api_url: https://236910733144.dkr.ecr.us-west-2.amazonaws.com
      prefix: 236910733144.dkr.ecr.us-west-2.amazonaws.com
      ping: yes
      insecure: no
#      credentials: ext:/scripts/login.sh
      credentials: 
        command: >-
	  HOME=/tmp aws ecr --region us-east-1 get-authorization-token
          --output text
          --query 'authorizationData[].authorizationToken'
          | base64 -d
      credsexpire: 6h

#authScripts:
#  enabled: true
#  scripts:
#      login.sh: |
#        #!/bin/sh
#        aws ecr --region "us-west-2" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

serviceAccount:
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::236910733144:role/sre-demo-dev-argocd-image-updater

